server:
  port: 9090

  
spring:
   mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
      
      
   datasource:
    username: root
    password: P@van@942
    url: jdbc:mysql://localhost:3306/stockApp
    
   jpa:
    properties:
     hibernate:
      format_sql: true
    show-sql: true 
    hibernate:
       ddl-auto: update
     
     
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
      base-path: "/my-actuator"
      
  endpoint:
    shutdown:
      enabled: true
      
  
        
         